Show the new point on the nearest wall
MPAMF/HomePlanner pull request #60
Opened 2024-05-09 11:51 UTC by SkelNeXus

2024-05-11 12:07 UTC, SkelNeXus commented
There is a bug on drag room, I need help to fix it @SchawnnDev

2024-05-12 11:20 UTC, SchawnnDev requested changes

2024-05-12 11:20 UTC, SchawnnDev commented on src/app/core/commands/wall-commands.ts
> +  private newWall: Wall | null = null;
```suggestion
  private newWall?: Wall;
```

2024-05-12 11:20 UTC, SchawnnDev commented on src/app/core/commands/wall-commands.ts
> +    private clickablePoint : ClickablePoint | undefined = undefined,
```suggestion
    private clickablePoint?: ClickablePoint,
```

2024-05-12 11:20 UTC, SchawnnDev commented on src/app/core/commands/wall-commands.ts
> +    if( this.clickablePoint == undefined ){
```suggestion
    if(!this.clickablePoint){
```

2024-05-12 11:20 UTC, SchawnnDev commented on src/app/core/models/board.ts
> +  public tempoDrawingElement: Drawable[];
```suggestion
  public tempDrawableElements: Drawable[];
```

2024-05-12 11:20 UTC, SchawnnDev commented on src/app/core/models/wall.ts
> +  isCorrectlyPrintOnWall (point : Point) {
```suggestion
  isPointOnSegment(point: Point) {
```

2024-05-12 11:31 UTC, SchawnnDev approved these changes

2024-05-13 10:05 UTC, merged